### ISSUE TITLE
Preprocessing Code

### ISSUE THREAD

**Issue by lousiming** [thswodnjs3/CSTA#2]
Could you please help me? I followed your preprocessing code and used the data format from the h5py file, but the results of my training are not very good. Could you provide some code for creating an h5py file? Thank you.

**Comment by thswodnjs3** [comment]
I'm very sorry but which data do you mean? The public dataset (SumMe, TVSum) or your custom dataset?

**Comment by lousiming** [comment]
I would like to know the code for processing two datasets, as they are quite different from each other. I haven't found any code online that handles both datasets. I went through the content in the h5 file and processed it myself, but when I trained the model, the scores were very low. I suspect that there might be an issue with my code or that the dataset I downloaded is slightly incomplete. Thank you for your reply. I am a student from China, and I would greatly appreciate your help in solving this problem.

**Comment by thswodnjs3** [comment]
I understand that you want to know two things.
1)The code preprocesses two public datasets and creates an h5py file.
2)Why is there a different result when you preprocess data yourself.

1)I've found that there is something quite similar.

https://github.com/li-plus/DSNet?tab=readme-ov-file#using-custom-videos

You can reference the link above.
But as you know it is not the official code and I haven't found the official code too.
So you need to consider it.

2)I suppose it is because the current h5py files were created using GoogleNet which had been implemented differently.
I'm not sure but I guess Ke Zhang (the author of vsLSTM, ECCV 2016) created h5py files using two datasets.
From his GitHub repository, he said that he used GoogleNet which was implemented by Caffe, not PyTorch.
Because of different implementations for GoogleNet, you might see different results.
You can reference below.

https://github.com/kezhang-cs/Video-Summarization-with-LSTM/issues/2

**Comment by lousiming** [comment]
Okay, thank you for your answer, I really appreciate it! I will take a look at the code first.
